import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Pricing } from "../components/Pricing/Pricing";
import { Slider } from "../components/Slider/Slider";
import styles from "../styles/Home.module.css";
import data from "../utils/data.json";

const Home: NextPage = () => {
  const [checked, setChecked] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Our Pricing</h1>
        <div className={styles.slider_container}>
          <p>Annually</p>
          <Slider checked={checked} setChecked={setChecked} />
          <p>Monthly</p>
        </div>
        <div className={styles.pricing_container}>
          {data.map((m) =>
            checked
              ? m.monthly.map((b) => <Pricing key={b.level} priceData={b} />)
              : m.annually.map((a) => <Pricing key={a.level} priceData={a} />)
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
